[build]
  publish = "public" # Ou "dist", "build", dependendo da ferramenta que você usa
  command = ""       # Adicione o comando de build necessário, se houver

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
