[build]
  publish = "." # Publicar da raiz do projeto
  command = ""  # Deixe em branco se não houver comando de build

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
